### PR TITLE
Create the spring-boot-app repository

### PR DESCRIPTION
**Pull request by raquel-campuzano**

### CODE REVIEW

**Review by vikram-bitnami — COMMENTED** [review]
Can you please also update the main README file for the repository with information on the new directory and the planned link to the tutorial?

**Comment by vikram-bitnami** [comment]
@beltran-rubo could you also check this PR, specifically if we need to add anything related to the license files as it is an Apache License project? Thanks.

**Comment by raquel-campuzano** [comment]
I included that license file since we are using part of the code of the Spring Boot official repo to create the WAR file. Let me know if it is necessary to indicate another thing or it is enough with that. Thanks!

**Review by vikram-bitnami — APPROVED** [review]
Looks OK, please fix typo and check with @beltran-rubo if we are OK keeping the license file as is.

**Pull request merged**
